Dockerfile

FROM golang:latest

LABEL maintainer="Prasoon Soni <prasoonsoni.work@gmail.com>"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main .

EXPOSE 8080

CMD ["./main"]


docker-compose.yaml
version: "3.6"
services:
  goservice:
    build: "."
    ports:
      - "8080"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "goservice"

nginx dockerfile
FROM nginx:latest
EXPOSE 80
COPY nginx.conf /etc/nginx/nginx.conf

nginx.conf
events {
    worker_connections 1024;
}
http {
  server_tokens off;
  server {
    listen 80;
    root  /var/www;

    location / {
      index index.html;
    }

    # Media: images, icons, video, audio, HTC
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
      expires 1d;
      access_log off;
      add_header Cache-Control "public";
    }

    # CSS and Javascript
    location ~* \.(?:css|js)$ {
      expires 1d;
      access_log off;
      add_header Cache-Control "public";
    }

    location /api/ {
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host            $http_host;
      proxy_pass http://goservice:8080/;
    }
  }
}